### ISSUE TITLE
Last updated on WP.org

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/simple-urls#2]
We're getting contacts regarding updating the plugin on WordPress.org.

This plugin hasn't been updated in over 2 years. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress.
Compatible up to: 3.5.2
Last Updated: 2013-1-17

cc @nathanrice

**Comment by nickcernis** [comment]
We continue to be asked about this, and the plugin is no longer appearing in WP.org search results:

https://wordpress.org/support/topic/update-needed-12/#post-9542607

![blank](https://user-images.githubusercontent.com/647669/31019094-81b9570e-a526-11e7-8acf-3da1c68de68e.png)

**Comment by dreamwhisper** [comment]
I see it just went for compatibility, closing.
