### ISSUE TITLE
updating .org repo

### ISSUE THREAD

**Issue by norcross** [copyblogger/simple-urls#4]
Any idea when this will be updated in the .org repo? the version here in GitHub has the filters for the post type registration that the .org version does not.

**Comment by bgardner** [comment]
Obviously a question for @nathanrice -- so I'll let him chime in.

**Comment by nathanrice** [comment]
Hm, that wasn't intentional. I'll get it pushed up to .org this week.

**Comment by norcross** [comment]
no worries. thanks y'all
